controller_manager_ns: ''
controller_list:
  - name: nao_dcm/RightArm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - RShoulderPitch
      - RShoulderYaw
      - RElbowRoll
      - RElbowYaw
  - name: nao_dcm/LeftArm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - LShoulderPitch
      - LShoulderYaw
      - LElbowRoll
      - LElbowYaw
  - name: nao_dcm/RightHand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - RWristRoll
      - RWristYaw
      - RWristPitch     
#      - RHand
#      - RFinger11
  - name: nao_dcm/LeftHand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - LWristRoll
      - LWristYaw
      - LWristPitch
#      - LHand
#      - LFinger11
  - name: nao_dcm/LeftLeg_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - LHipYaw
      - LHipRoll
      - LHipPitch
      - LKneePitch
      - LAnklePitch
      - LAnkleRoll
 #     - LToePitch
  - name: nao_dcm/RightLeg_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - RHipYaw
      - RHipRoll
      - RHipPitch
      - RKneePitch
      - RAnklePitch
      - RAnkleRoll
 #     - RToePitch
  - name: nao_dcm/Head_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - NeckYaw
      - NeckPitch
      - HeadPitch
      - HeadRoll
